#+title: Engrave Faces
#+author: tecosaur

#+html: <p><a href="http://elpa.gnu.org/packages/engrave-faces.html"><img alt="GNU ELPA" src="https://elpa.gnu.org/packages/engrave-faces.svg"/></a>
#+html: <img src="https://img.shields.io/badge/stage-%CE%B2,%20refinement-orange?style=flat-square">
#+html: <a href="http://elpa.gnu.org/devel/engrave-faces.html"><img alt="GNU-devel ELPA" src="https://elpa.gnu.org/devel/engrave-faces.svg"/></a></p>

There are some great packages for Exporting buffers to particular formats, but
each one seems to reinvent the core mechanism of processing the font-lock in a
buffer such that it can be exported to a particular format.

This package aims to produce a versatile generic core which can process a
fontified buffer and elegantly pass the data to any number of backends which can
deal with specific output formats.

This is very much a work in progress, a rough plan can be seen below.
I fully expect some important items to have been forgotten.

*Font lock processing*
- [X] Single faces
- [X] Merge multiple faces
- [ ] Process overlays

*Included backends*
- [X] LaTeX
- [X] HTML
- [X] ANSI

* Fork changes

Changes made in this fork relative to upstream [[https://github.com/tecosaur/engrave-faces][tecosaur/engrave-faces]]:

- Hex color validation added to preset loading (upstream PR #22)
- =nepes-dark= and =nepes-light= preset themes derived from the Nepes brand palette

* Related

- [[https://github.com/kayspark/nepes-palette][nepes-palette]] — single source of truth for all Nepes themes
- [[https://github.com/kayspark/emacs-nepes][emacs-nepes]] — Emacs theme whose face values feed these presets
- [[https://github.com/kayspark/nepes-latex-template][nepes-latex-template]] — LaTeX template that uses engrave-faces for code export
